# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4141b2647305091a5fa3f6445af86a7ae7ccc4edae7cc9e14553bc4d5d39677b3fd3e7041c296f51205b1c4ee208fb82aca90ddd817e91d3d51cc100a7c90be

test:
  secret_key_base: 77fa5d225132e84cfdd1f8639e6910e85d33108b4bb5ed44007c8ebf5e4fc1968ecb294019e7d5f23f97fcd829eb2dd1e9f94186fd464a50eaec178452183379

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
